### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by ymx0723** [DSIMB/SWORD2#1]
Hi,when i running SWORD2.py, I encountered the following error：
Traceback (most recent call last):
  File "/data/run01/scz4082/soft/SWORD2/./SWORD2.py", line 598, in <module>
    write_peeling_results()
  File "/data/run01/scz4082/soft/SWORD2/./SWORD2.py", line 391, in write_peeling_results
    with open(peeling_num, "r") as f:
NotADirectoryError: [Errno 20] Not a directory: 'results/1jx4_A_07_10_2022_88289/1jx4_A/1jx4_A.num'
I even failed with the example provided.

**Comment by gabrielctn** [comment]
Hi,
Can you please give your OS, and command line you run that gives this issue ?
Also, the paths `/data/...` looks strange, where did you clone and installed SWORD2 repo ?

**Comment by ymx0723** [comment]
Hi,
Here is my OS information "Linux debian-07 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64 GNU/Linux"
The command line is "./SWORD2.py -p 1jx4 -o results"
I downloaded the zip from "https://github.com/DSIMB/SWORD2" and installed in my OS

**Comment by gabrielctn** [comment]
Okay, and are you running SWORD2 inside the conda environment ?

**Comment by ymx0723** [comment]
yeah,i run the command line inside the conda environment

**Comment by gabrielctn** [comment]
Hmm that is strange I am unable to reproduce the error.
Do you have the same issue using docker ?
Can you please run the following command: `docker run -it --rm -v /data/run01/scz4082/soft/SWORD2/results:/sword2/results dsimb/sword2 -p 1jx4 -o results` ?
Thank you !

**Comment by JudeWells** [comment]
I also had the same error when attempting to run in the Conda environment (Using Mac OS):

(sword2) judewells % ./SWORD2.py -p 1jx4 -o results   
2022/11/02 10:23:57 INFO     Fetch PDB ID: 1jx4
2022/11/02 10:23:57 DEBUG    Connecting wwPDB FTP server RCSB PDB (USA).
2022/11/02 10:23:59 DEBUG    1jx4 downloaded (results/1jx4_A/1jx4.pdb)
2022/11/02 10:23:59 DEBUG    PDB download via FTP completed (1 downloaded, 0 failed).
2022/11/02 10:23:59 DEBUG    3162 atoms and 1 coordinate set(s) were parsed in 0.02s.
2022/11/02 10:23:59 INFO     Estimated runtime: 4 minutes
2022/11/02 10:23:59 INFO     Write a clean version of the PDB: remove non standard residues
2022/11/02 10:23:59 INFO     Launch SWORD
2022/11/02 10:24:00 INFO     Parse SWORD output
2022/11/02 10:24:00 INFO     Calculate pseudo-energies of Domains
2022/11/02 10:24:01 INFO     Write the SWORD results
Traceback (most recent call last):
  File "/Users/judewells/.../SWORD2/./SWORD2.py", line 598, in <module>
    write_peeling_results()
  File "/Users/judewells/.../SWORD2/./SWORD2.py", line 391, in write_peeling_results
    with open(peeling_num, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/1jx4_A/PDBs_Clean/1jx4_A/1jx4_A.num'

**Comment by JudeWells** [comment]
When I try:
cd results/1jx4_A/PDBs_Clean/1jx4_A
I get:
cd: no such file or directory: results/1jx4_A/PDBs_Clean/1jx4_A

After running the above command and getting the error my file structure looks like this:
% cd results/1jx4_A/PDBs_Clean
% ls
XXXX
% cd XXXX
% ls
Peeling		XXXX.dssp	XXXX.fasta	XXXX.num	XXXX.pdb	XXXX.s2d

**Comment by gabrielctn** [comment]
Is it an Intel or M1/M2 apple product ?
Also, can you please provide the macOS version you are running ?
Thanks

**Comment by JudeWells** [comment]
M1 MacBook Pro running Mac OS Monterey 12.5.1

**Comment by gabrielctn** [comment]
Alright I might have a hint of the issue.
Can you try running the Peeling executable:
```
./bin/SWORD/bin/SWORD/bin/Peeling1141_macos_intel_arm64
```
And tell me if you get an error?

**Comment by JudeWells** [comment]
% ./bin/SWORD/bin/SWORD/bin/Peeling1141_macos_intel_arm64

dyld[29640]: Library not loaded: '@rpath/libclang_rt.asan_osx_dynamic.dylib'
  Referenced from: '/Users/judewells/.../SWORD2/bin/SWORD/bin/SWORD/bin/Peeling1141_macos_intel_arm64'
  Reason: tried: '/Users/judewells/.../SWORD2/bin/SWORD/bin/SWORD/bin/libclang_rt.asan_osx_dynamic.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib' (no such file), '/Users/judewells/.../SWORD2/bin/SWORD/bin/SWORD/bin/libclang_rt.asan_osx_dynamic.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib' (no such file), '/usr/local/lib/libclang_rt.asan_osx_dynamic.dylib' (no such file), '/usr/lib/libclang_rt.asan_osx_dynamic.dylib' (no such file)
zsh: abort      ./bin/SWORD/bin/SWORD/bin/Peeling1141_macos_intel_arm64

**Comment by gabrielctn** [comment]
Alright, then the problem comes from the compiled version of this program. It was compiled for versions up to macOS 12 only, which looks for the version 13 of the compiler clang. I will look at how to compile it statically to fix this issue.
I do reproduce this error on macOS 13 Ventura, which has clang 14 installed.

**Comment by gabrielctn** [comment]
Hi @ymx0723 and @JudeWells 
Can you please reinstall the repo from scratch and run the install script that I just added by doing `bash install.sh` as I just added in the README ?
It should fix things, especially for Apple.

**Comment by gabrielctn** [comment]
The release 1.1.0 should have fixed the issues.
Please open another issue if something is wrong.

**Comment by JudeWells** [comment]
The latest release seems to be working perfectly - Thank you!
