### ISSUE TITLE
Index Error Occurence

### ISSUE THREAD

**Issue by alexandrosangeli** [DSIMB/SWORD2#2]
Hello,

Thanks for making the repository public.

I've left a BASH script run overnight on some chains and found this error in the log in the morning:
```

Traceback (most recent call last):
  File "/foo/SWORD2/./SWORD2.py", line 614, in <module>
    pus_colors, dom_colors = define_colors(sword_results)
  File "/foo/SWORD2/./SWORD2.py", line 275, in define_colors
    hex_val = colors_for_pus[color_pu_cnt].lstrip("#")
IndexError: list index out of range
```

Not sure on what sequence this has occurred but can provide further information if needed.

**Comment by gabrielctn** [comment]
Hi, thanks for using our tool !

I don't know if this is linked to the other issue #3 you submitted, but could you try again with the new release v1.1.1 ?
thanks

**Comment by alexandrosangeli** [comment]
I'm now getting the following errors:

```
Traceback (most recent call last):
  File "/home/aangeli/sword_workspace/SWORD2/./SWORD2.py", line 714, in <module>
    write_partitionings(sword_results, energies)
  File "/foo//SWORD2/./SWORD2.py", line 277, in write_partitionings
    f.write(f"""Domain:{i+1}       AUL={int((1-(1/(energies[(nb_alt_part, i)][1])**2))*100) if abs(energies[(nb_alt_part, i)][1]) >= 1 else 0:3}% Z-score={round(energies[(nb_alt_part, i)][1], 1)}\n""")
  File "<string>", line 2, in __getitem__
  File "/foo/anaconda3/envs/sword2/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
    raise convert_to_error(kind, result)
KeyError: (0, 0)
```

**Comment by gabrielctn** [comment]
Sorry for the late reply.
Would you mind telling me what PDB file you are trying to analyze so that I can try to see on my side what could be the issue ?
Thanks

**Comment by alexandrosangeli** [comment]
Hi, sorry about the inconvenience, the error was on my end as I didn't run `bash install.sh` after I pulled the updates. When I run it i stopped getting this particular error (KeyError). However I still got an an index error but can't point you to the exact PDB file that caused this as I was running the script over a very large number of files (approx. 900) over night. I can send over the list of PDBs if needed or I can re-run the script when I get the chance and log the errors with the respective PDB file that the script was running on.

**Comment by gabrielctn** [comment]
Alright then, good to hear!

Yeah if you have the chance to re-run the script and log the pdb, because it looks like a particular exception that I probably missed, so without the exact example I will have a hard time to fix it. I suspect that the protein is particularly big with a large number of domains and PUs and therefore there is a lack of colors in stock, but I can't be sure.

**Comment by gabrielctn** [comment]
I'll close this issue, reopen it if necessary.
