### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by wh277** [DSIMB/SWORD2#4]
I met a similar bug with the closed issue, but it is Errno 2.
Traceback (most recent call last):
  File "/home/...../SWORD2-1.1.1/./SWORD2.py", line 718, in &lt;module&gt;
    write_peeling_results()
  File "/home/...../SWORD2-1.1.1/./SWORD2.py", line 437, in write_peeling_results
    with open(peeling_num, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/....../A_A_13_03_2023_66722/PDBs_Clean/A_A/A_A.num'

**Comment by gabrielctn** [comment]
This means that the Peeling program inside SWORD didn't run successfully.
Did you run `bash install.sh` before running `SWORD2.py` ?

**Comment by wh277** [comment]
yes，I had run bash install.sh. I tried again, it was no problem with 1jx4,  but failed with my PDB. 
Thanks
![225154](https://user-images.githubusercontent.com/125532384/225939801-66f5af50-9f4e-4b0a-82b2-5e7f181f97b0.png)

![211](https://user-images.githubusercontent.com/125532384/225939775-8ee2f119-0c55-4767-aa49-ee2f9925c0cf.png)

![微信图片_20230317222815](https://user-images.githubusercontent.com/125532384/225933407-db1f550b-59c3-4c07-b0b8-c66c16fdec93.png)

**Comment by gabrielctn** [comment]
Alright, and what do the files `results/0_A/sword.txt` and `results/0_A/SWORD2_summary.txt` contain ?
Is there anything in the `results/0_A/SWORD/0_A/` directory ?

**Comment by wh277** [comment]
Nothing in sword.txt  
![12](https://user-images.githubusercontent.com/125532384/225943637-208bde16-5e1e-4b44-bcd7-72400e6daf4a.jpg)
[SWORD2_summary.txt](https://github.com/DSIMB/SWORD2/files/11002699/SWORD2_summary.txt)

**Comment by gabrielctn** [comment]
Strange ... would you mind sending me your PDB file so that I can investigate further ? Either her or by email (c.f my profile) if you prefer ?

**Comment by wh277** [comment]
OK, I will send to your email
