### ISSUE TITLE
 install problem

### ISSUE THREAD

**Issue by lzbsjtu** [DSIMB/SWORD2#6]
bash install.sh
Error: unable to compile necessary dependancies for SWORD
I met this problem, when installing. I don`t know how to continue. may you help me?
I believe this software will help me a lot for my study on protein domain. Thanks a lot.

**Comment by gabrielctn** [comment]
Hi, thanks for your interest in SWORD2 !
It looks like it was unable to run the compilation file `bin/SWORD/bin/SWORD/bin/Dssp/DsspCompileCC`
Can you try to run it independently to see the error it gives ?
Also, can you tell me what is your OS ?

**Comment by lzbsjtu** [comment]
thanks a lot for your guidance.
I run it independently and it worked. And I rerun 'bash install.sh'.
My OS is Linux.
thank you again.
