### ISSUE TITLE
Hello, what is the reason for the error when executing the following command? docker run --rm -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v $(pwd)/results:/output dsimb/ sword2:latest -p 1jx4 -o /output

### ISSUE THREAD

**Issue by Yunchuan01** [DSIMB/SWORD2#9]
![image](https://github.com/user-attachments/assets/e8a6eafb-55b4-4717-aa73-0d512e801cd1)

**Comment by gabrielctn** [comment]
Hi, sorry for the error. I forgot to remove precompiled binaries before building the docker image so linking was bad.
I just pushed a new image, can you try again after pulling the newest image `docker pull dsimb/sword2:latest` ?
Thanks
